---
title: "Who Does More Pushups"
author: "Diana Reyes"
date: "October 30, 2020"
output:
html_document:
number_sections: true
toc: true
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
data("pushups")
```

# Introduction

<!--In this section you explain what you are trying to show. Where did the data come from? What is the research or other question you are trying to answer?!-->

$H_0$ Null Hypothesis is there is no difference between the average number of pushups of line vs skill players   

$H_A$The average number of pushups done by line players is statistically different than that of skill players. 

The required data is provided in a file called "pushups" in which will help me find out if the $H_0$ or $H_A$ is correct. The position of the player will be used as well as the categories of line and skill to uncover if there is a difference in regards to how many pushups they can do based on their position. 

# Methods

<!--Decide on your methods: use "variable analysis" or other appropriate descriptors. Make sure to choose at least one graphical method and at least one numerical method.!-->

Numerical~cat will be used to obtain information based on the charts since pushups are considered numerical and position is categorical therefore Numerical-Cat is the best option to find our answer.

# Results

<!--Divide this section into two sub-sections: One for your descriptive results and one for your inferential results.!-->

## Descriptive Results

### Graphical Descriptive Results

<!--Graphical results here. Make sure to show your code. Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too. Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->

 


### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

## Inferential Results

<!--State hypothesis clearly. Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc. Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion

<!--Discussion and conclusion here. If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason. Watch the chapter 6 videos from the GeorgeTown videos collection.!-->

When your markdown file successfully knits and you are satisfied with your results, then push your work back to your github repository and submit the link to your github repo to canvas  to complete this assignment.